# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/hgiesel/Developer/repos/anki_stats_plus/designer/graph_list.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GraphList(object):
    def setupUi(self, GraphList):
        GraphList.setObjectName("GraphList")
        GraphList.resize(518, 242)
        self.verticalLayout = QtWidgets.QVBoxLayout(GraphList)
        self.verticalLayout.setObjectName("verticalLayout")
        self.list = QtWidgets.QListWidget(GraphList)
        self.list.setDragEnabled(True)
        self.list.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.list.setAlternatingRowColors(True)
        self.list.setMovement(QtWidgets.QListView.Snap)
        self.list.setProperty("isWrapping", False)
        self.list.setResizeMode(QtWidgets.QListView.Fixed)
        self.list.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.list.setViewMode(QtWidgets.QListView.ListMode)
        self.list.setSelectionRectVisible(True)
        self.list.setObjectName("list")
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.list.addItem(item)
        self.verticalLayout.addWidget(self.list)

        self.retranslateUi(GraphList)
        QtCore.QMetaObject.connectSlotsByName(GraphList)

    def retranslateUi(self, GraphList):
        _translate = QtCore.QCoreApplication.translate
        GraphList.setWindowTitle(_translate("GraphList", "Form"))
        self.list.setSortingEnabled(False)
        __sortingEnabled = self.list.isSortingEnabled()
        self.list.setSortingEnabled(False)
        item = self.list.item(0)
        item.setText(_translate("GraphList", "Added Graph"))
        item = self.list.item(1)
        item.setText(_translate("GraphList", "Answer Buttons"))
        item = self.list.item(2)
        item.setText(_translate("GraphList", "Calendar Graph"))
        item = self.list.item(3)
        item.setText(_translate("GraphList", "Card Counts"))
        item = self.list.item(4)
        item.setText(_translate("GraphList", "Card Ease Graph"))
        item = self.list.item(5)
        item.setText(_translate("GraphList", "Future Due"))
        item = self.list.item(6)
        item.setText(_translate("GraphList", "Hourly Breakdown"))
        item = self.list.item(7)
        item.setText(_translate("GraphList", "Review Intervals"))
        item = self.list.item(8)
        item.setText(_translate("GraphList", "Reviews Graph"))
        item = self.list.item(9)
        item.setText(_translate("GraphList", "Today Stats"))
        self.list.setSortingEnabled(__sortingEnabled)
