# Form implementation generated from reading ui file 'C:\Users\shigg\AppData\Roaming\Anki2\addons21\stats plus fork by Shige\anki_stats_plus-master\designer\settings.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(670, 406)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Settings)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(parent=Settings)
        self.tabWidget.setObjectName("tabWidget")
        self.deckbrowser_tab = QtWidgets.QWidget()
        self.deckbrowser_tab.setObjectName("deckbrowser_tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.deckbrowser_tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.deckBrowser = GraphList(parent=self.deckbrowser_tab)
        self.deckBrowser.setObjectName("deckBrowser")
        self.verticalLayout.addWidget(self.deckBrowser)
        self.tabWidget.addTab(self.deckbrowser_tab, "")
        self.overview_tab = QtWidgets.QWidget()
        self.overview_tab.setObjectName("overview_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.overview_tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.deckOverview = GraphList(parent=self.overview_tab)
        self.deckOverview.setObjectName("deckOverview")
        self.verticalLayout_2.addWidget(self.deckOverview)
        self.tabWidget.addTab(self.overview_tab, "")
        self.congrats_tab = QtWidgets.QWidget()
        self.congrats_tab.setObjectName("congrats_tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.congrats_tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.congratsPage = GraphList(parent=self.congrats_tab)
        self.congratsPage.setObjectName("congratsPage")
        self.verticalLayout_4.addWidget(self.congratsPage)
        self.tabWidget.addTab(self.congrats_tab, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Settings)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)

        self.retranslateUi(Settings)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(Settings.accept) # type: ignore
        self.buttonBox.rejected.connect(Settings.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Dialog"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.deckbrowser_tab), _translate("Settings", "Deck Browser"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.overview_tab), _translate("Settings", "Deck Overview"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.congrats_tab), _translate("Settings", "Congrats Page"))
from ..graph_list import GraphList
